import 'package:country_pickers/country.dart';

List<Country> countryList = [
  ["AF", "Afghanistan", "阿富汗", "93"],
  ["AX", "Åland Islands", "奥兰", "358"],
  ["AL", "Albania", "阿尔巴尼亚", "355"],
  ["DZ", "Algeria", "阿尔及利亚", "213"],
  ["AS", "American Samoa", "美属萨摩亚", "1-684"],
  ["AD", "Andorra", "安道尔", "376"],
  ["AO", "Angola", "安哥拉", "244"],
  ["AI", "Anguilla", "安圭拉", "1-264"],
  ["AQ", "Antarctica", "南极洲", "672"],
  ["AG", "Antigua and Barbuda", "安地卡及巴布达", "1-268"],
  ["AR", "Argentina", "阿根廷", "54"],
  ["AM", "Armenia", "亚美尼亚", "374"],
  ["AW", "Aruba", "阿鲁巴", "297"],
  ["AU", "Australia", "澳大利亚", "61"],
  ["AT", "Austria", "奥地利", "43"],
  ["AZ", "Azerbaijan", "阿塞拜疆", "994"],
  ["BS", "Bahamas", "巴哈马", "1-242"],
  ["BH", "Bahrain", "巴林", "973"],
  ["BD", "Bangladesh", "孟加拉国", "880"],
  ["BB", "Barbados", "巴巴多斯", "1-246"],
  ["BY", "Belarus", "白俄罗斯", "375"],
  ["BE", "Belgium", "比利时", "32"],
  ["BZ", "Belize", "伯利兹", "501"],
  ["BJ", "Benin", "贝宁", "229"],
  ["BM", "Bermuda", "百慕大", "1-441"],
  ["BT", "Bhutan", "不丹", "975"],
  ["BO", "Bolivia", "玻利维亚", "591"],
  ["BQ", "Bonaire, Sint Eustatius and Saba", "加勒比荷兰", "599"],
  ["BA", "Bosnia and Herzegovina", "波斯尼亚和黑塞哥维那", "387"],
  ["BW", "Botswana", "博茨瓦纳", "267"],
  ["BV", "Bouvet Island", "布韦岛", "47"],
  ["BR", "Brazil", "巴西", "55"],
  ["IO", "British Indian Ocean Territory", "英属印度洋领地", "246"],
  ["BN", "Brunei Darussalam", "文莱", "673"],
  ["BG", "Bulgaria", "保加利亚", "359"],
  ["BF", "Burkina Faso", "布吉纳法索", "226"],
  ["BI", "Burundi", "布隆迪", "257"],
  ["KH", "Cambodia", "柬埔寨", "855"],
  ["CM", "Cameroon", "喀麦隆", "237"],
  ["CA", "Canada", "加拿大", "1"],
  ["CV", "Cape Verde", "佛得角", "238"],
  ["KY", "Cayman Islands", "开曼群岛", "1-345"],
  ["CF", "Central African Republic", "中非", "236"],
  ["TD", "Chad", "乍得", "235"],
  ["CL", "Chile", "智利", "56"],
  ["CN", "China", "中国", "86"],
  ["CX", "Christmas Island", "圣诞岛", "61"],
  ["CC", "Cocos (Keeling) Islands", "科科斯（基林）群岛", "61"],
  ["CO", "Colombia", "哥伦比亚", "57"],
  ["KM", "Comoros", "科摩罗", "269"],
  ["CG", "Congo", "刚果（布)", "242"],
  ["CD", "Congo, the Democratic Republic of the", "刚果（金)", "243"],
  ["CK", "Cook Islands", "库克群岛", "682"],
  ["CR", "Costa Rica", "哥斯达黎加", "506"],
  ["CI", "Cote D'Ivoire", "科特迪瓦", "225"],
  ["HR", "Croatia", "克罗地亚", "385"],
  ["CU", "Cuba", "古巴", "53"],
  ["CW", "Curaçao", "库拉索", "599"],
  ["CY", "Cyprus", "赛普勒斯", "357"],
  ["CZ", "Czech Republic", "捷克", "420"],
  ["DK", "Denmark", "丹麦", "45"],
  ["DJ", "Djibouti", "吉布提", "253"],
  ["DM", "Dominica", "多米尼克", "1-767"],
  ["DO", "Dominican Republic", "多米尼加", ""],
  ["EC", "Ecuador", "厄瓜多尔", "593"],
  ["EG", "Egypt", "埃及", "20"],
  ["SV", "El Salvador", "萨尔瓦多", "503"],
  ["GQ", "Equatorial Guinea", "赤道几内亚", "240"],
  ["ER", "Eritrea", "厄立特里亚", "291"],
  ["EE", "Estonia", "爱沙尼亚", "372"],
  ["ET", "Ethiopia", "衣索比亚", "251"],
  ["FK", "Falkland Islands (Malvinas)", "福克兰群岛", "500"],
  ["FO", "Faroe Islands", "法罗群岛", "298"],
  ["FJ", "Fiji", "斐济", "679"],
  ["FI", "Finland", "芬兰", "358"],
  ["FR", "France", "法国", "33"],
  ["GF", "French Guiana", "法属圭亚那", "594"],
  ["PF", "French Polynesia", "法属玻里尼西亚", "689"],
  ["TF", "French Southern Territories", "法属南部领地", "262"],
  ["GA", "Gabon", "加彭", "241"],
  ["GM", "Gambia", "冈比亚", "220"],
  ["GE", "Georgia", "格鲁吉亚", "995"],
  ["DE", "Germany", "德国", "49"],
  ["GH", "Ghana", "加纳", "233"],
  ["GI", "Gibraltar", "直布罗陀", "350"],
  ["GR", "Greece", "希腊", "30"],
  ["GL", "Greenland", "格陵兰", "299"],
  ["GD", "Grenada", "格瑞那达", "1-473"],
  ["GP", "Guadeloupe", "瓜德罗普", "590"],
  ["GU", "Guam", "关岛", "1-671"],
  ["GT", "Guatemala", "危地马拉", "502"],
  ["GG", "Guernsey", "根西", "44"],
  ["GN", "Guinea", "几内亚", "224"],
  ["GW", "Guinea-Bissau", "几内亚比绍", "245"],
  ["GY", "Guyana", "圭亚那", "592"],
  ["HT", "Haiti", "海地", "509"],
  ["HM", "Heard Island and Mcdonald Islands", "赫德岛和麦克唐纳群岛", "672"],
  ["VA", "Holy See (Vatican City State)", "梵蒂冈", "39-06"],
  ["HN", "Honduras", "宏都拉斯", "504"],
  ["HK", "Hong Kong", "香港", "852"],
  ["HU", "Hungary", "匈牙利", "36"],
  ["IS", "Iceland", "冰岛", "354"],
  ["IN", "India", "印度", "91"],
  ["ID", "Indonesia", "印尼", "62"],
  ["IR", "Iran, Islamic Republic of", "伊朗", "98"],
  ["IQ", "Iraq", "伊拉克", "964"],
  ["IE", "Ireland", "爱尔兰", "353"],
  ["IM", "Isle of Man", "马恩岛", "44"],
  ["IL", "Israel", "以色列", "972"],
  ["IT", "Italy", "意大利", "39"],
  ["JM", "Jamaica", "牙买加", "1-876"],
  ["JP", "Japan", "日本", "81"],
  ["JE", "Jersey", "泽西", "44"],
  ["JO", "Jordan", "约旦", "962"],
  ["KZ", "Kazakhstan", "哈萨克斯坦", "7"],
  ["KE", "Kenya", "肯尼亚", "254"],
  ["KI", "Kiribati", "基里巴斯", "686"],
  ["KP", "North Korea", "朝鲜", "850"],
  ["KR", "South Korea", "韩国", "82"],
  ["KW", "Kuwait", "科威特", "965"],
  ["KG", "Kyrgyzstan", "吉尔吉斯斯坦", "996"],
  ["LA", "Lao People's Democratic Republic", "老挝", "856"],
  ["LV", "Latvia", "拉脱维亚", "371"],
  ["LB", "Lebanon", "黎巴嫩", "961"],
  ["LS", "Lesotho", "赖索托", "266"],
  ["LR", "Liberia", "利比里亚", "231"],
  ["LY", "Libya", "利比亚", "218"],
  ["LI", "Liechtenstein", "列支敦斯登", "423"],
  ["LT", "Lithuania", "立陶宛", "370"],
  ["LU", "Luxembourg", "卢森堡", "352"],
  ["MO", "Macao", "澳门", "853"],
  ["MK", "North Macedonia, Republic of", "北马其顿", "389"],
  ["MG", "Madagascar", "马达加斯加", "261"],
  ["MW", "Malawi", "马拉维", "265"],
  ["MY", "Malaysia", "马来西亚", "60"],
  ["MV", "Maldives", "马尔地夫", "960"],
  ["ML", "Mali", "马里", "223"],
  ["MT", "Malta", "马尔他", "356"],
  ["MH", "Marshall Islands", "马绍尔群岛", "692"],
  ["MQ", "Martinique", "马提尼克", "596"],
  ["MR", "Mauritania", "毛里塔尼亚", "222"],
  ["MU", "Mauritius", "模里西斯", "230"],
  ["YT", "Mayotte", "马约特", "262"],
  ["MX", "Mexico", "墨西哥", "52"],
  ["FM", "Micronesia, Federated States of", "密克罗尼西亚联邦", "691"],
  ["MD", "Moldova, Republic of", "摩尔多瓦", "373"],
  ["MC", "Monaco", "摩纳哥", "377"],
  ["MN", "Mongolia", "蒙古", "976"],
  ["ME", "Montenegro", "蒙特内哥罗", "382"],
  ["MS", "Montserrat", "蒙特塞拉特", "1-664"],
  ["MA", "Morocco", "摩洛哥", "212"],
  ["MZ", "Mozambique", "莫桑比克", "258"],
  ["MM", "Myanmar", "缅甸", "95"],
  ["NA", "Namibia", "纳米比亚", "264"],
  ["NR", "Nauru", "瑙鲁", "674"],
  ["NP", "Nepal", "尼泊尔", "977"],
  ["NL", "Netherlands", "荷兰", "31"],
  ["NC", "New Caledonia", "新喀里多尼亚", "687"],
  ["NZ", "New Zealand", "新西兰", "64"],
  ["NI", "Nicaragua", "尼加拉瓜", "505"],
  ["NE", "Niger", "尼日尔", "227"],
  ["NG", "Nigeria", "奈及利亚", "234"],
  ["NU", "Niue", "纽埃", "683"],
  ["NF", "Norfolk Island", "诺福克岛", "672"],
  ["MP", "Northern Mariana Islands", "北马里亚纳群岛", "1-670"],
  ["NO", "Norway", "挪威", "47"],
  ["OM", "Oman", "阿曼", "968"],
  ["PK", "Pakistan", "巴基斯坦", "92"],
  ["PW", "Palau", "帛琉", "680"],
  ["PS", "Palestinian Territory, Occupied", "巴勒斯坦", "970"],
  ["PA", "Panama", "巴拿马", "507"],
  ["PG", "Papua New Guinea", "巴布亚新几内亚", "675"],
  ["PY", "Paraguay", "巴拉圭", "595"],
  ["PE", "Peru", "秘鲁", "51"],
  ["PH", "Philippines", "菲律宾", "63"],
  ["PN", "Pitcairn", "皮特凯恩群岛", "870"],
  ["PL", "Poland", "波兰", "48"],
  ["PT", "Portugal", "葡萄牙", "351"],
  ["PR", "Puerto Rico", "波多黎各", "1"],
  ["QA", "Qatar", "卡塔尔", "974"],
  ["RE", "Reunion", "留尼汪", "262"],
  ["RO", "Romania", "罗马尼亚", "40"],
  ["RU", "Russian Federation", "俄罗斯", "7"],
  ["RW", "Rwanda", "卢旺达", "250"],
  ["BL", "Saint Barthélemy", "圣巴泰勒米", "590"],
  ["SH", "Saint Helena", "圣赫勒拿", "290"],
  ["KN", "Saint Kitts and Nevis", "圣基茨和尼维斯", "1-869"],
  ["LC", "Saint Lucia", "圣卢西亚", "1-758"],
  ["MF", "Saint Martin (French part)", "法属圣马丁", "590"],
  ["PM", "Saint Pierre and Miquelon", "圣皮埃尔和密克隆", "508"],
  ["VC", "Saint Vincent and the Grenadines", "圣文森及格瑞那丁", "1-784"],
  ["WS", "Samoa", "萨摩亚", "685"],
  ["SM", "San Marino", "圣马力诺", "378"],
  ["ST", "Sao Tome and Principe", "圣多美和普林西比", "239"],
  ["SA", "Saudi Arabia", "沙乌地阿拉伯", "966"],
  ["SN", "Senegal", "塞内加尔", "221"],
  ["RS", "Serbia", "塞尔维亚", "381"],
  ["SC", "Seychelles", "塞舌尔", "248"],
  ["SL", "Sierra Leone", "塞拉利昂", "232"],
  ["SG", "Singapore", "新加坡", "65"],
  ["SX", "Sint Maarten (Dutch part)", "荷属圣马丁", "1-721"],
  ["SK", "Slovakia", "斯洛伐克", "421"],
  ["SI", "Slovenia", "斯洛维尼亚", "386"],
  ["SB", "Solomon Islands", "所罗门群岛", "677"],
  ["SO", "Somalia", "索马利亚", "252"],
  ["ZA", "South Africa", "南非", "27"],
  ["GS", "South Georgia and the South Sandwich Islands", "南乔治亚和南桑威奇群岛", "500"],
  ["SS", "South Sudan", "南苏丹", "211"],
  ["ES", "Spain", "西班牙", "34"],
  ["LK", "Sri Lanka", "斯里兰卡", "94"],
  ["SD", "Sudan", "苏丹", "249"],
  ["SR", "Suriname", "苏里南", "597"],
  ["SJ", "Svalbard and Jan Mayen", "斯瓦尔巴群岛和扬马延岛", "47"],
  ["SZ", "Swaziland", "斯威士兰", "268"],
  ["SE", "Sweden", "瑞典", "46"],
  ["CH", "Switzerland", "瑞士", "41"],
  ["SY", "Syrian Arab Republic", "叙利亚", "963"],
  ["TW", "Taiwan", "臺湾", "886"],
  ["TJ", "Tajikistan", "塔吉克斯坦", "992"],
  ["TZ", "Tanzania, United Republic of", "坦桑尼亚", "255"],
  ["TH", "Thailand", "泰国", "66"],
  ["TL", "Timor-Leste", "东帝汶", "670"],
  ["TG", "Togo", "多哥", "228"],
  ["TK", "Tokelau", "托克劳", "690"],
  ["TO", "Tonga", "汤加", "676"],
  ["TT", "Trinidad and Tobago", "千里达及托巴哥", "1-868"],
  ["TN", "Tunisia", "突尼西亚", "216"],
  ["TR", "Turkey", "土耳其", "90"],
  ["TM", "Turkmenistan", "土库曼斯坦", "993"],
  ["TC", "Turks and Caicos Islands", "特克斯和凯科斯群岛", "1-649"],
  ["TV", "Tuvalu", "图瓦卢", "688"],
  ["UG", "Uganda", "乌干达", "256"],
  ["UA", "Ukraine", "乌克兰", "380"],
  ["AE", "United Arab Emirates", "阿联酋", "971"],
  ["GB", "United Kingdom", "英国", "44"],
  ["US", "United States of America", "美国", "1"],
  ["UM", "United States Minor Outlying Islands", "美国本土外小岛屿", " "],
  ["UY", "Uruguay", "乌拉圭", "598"],
  ["UZ", "Uzbekistan", "乌兹别克斯坦", "998"],
  ["VU", "Vanuatu", "瓦努阿图", "678"],
  ["VE", "Venezuela", "委内瑞拉", "58"],
  ["VN", "Viet Nam", "越南", "84"],
  ["VG", "Virgin Islands, British", "英属维尔京群岛", "1-284"],
  ["VI", "Virgin Islands, U.S.", "美属维尔京群岛", "1-340"],
  ["WF", "Wallis and Futuna", "瓦利斯和富图纳", "681"],
  ["EH", "Western Sahara", "阿拉伯撒哈拉民主共和国", "212"],
  ["YE", "Yemen", "叶门", "967"],
  ["ZM", "Zambia", "尚比亚", "260"],
  ["ZW", "Zimbabwe", "辛巴威", "263"],
  ["XK", "Kosovo", "科索沃", ""]
]
    .map((v) =>
        Country(isoCode: v[0], nameEn: v[1], nameZh: v[2], phoneCode: v[3]))
    .toList();
